name: 'Build Container image for Humanitec'
description: 'Build Docker image with docker cache'
inputs:
  humanitec_token:
    description: 'humanitec token'
    required: true
  humanitec_org:
    description: 'humanitec org'
    required: true
  image_name:
    description: 'image name'
    required: true
    default: ${{ github.event.repository.name }}
  local_tag:
    description: 'image tag on Github Action'
    required: true
    default: latest

runs:
  using: "composite"
  steps:
    - name: Push to Humanitec
      run: ${{ github.action_path }}/../scripts/push-to-humanitec.sh ${{ inputs.humanitec_org }} ${{ inputs.humanitec_token }} ${{ inputs.image_name }} ${{ inputs.local_tag }}
      shell: sh
