name: 'Push image to Humanitec'
description: 'Push image to Humanitec'
inputs:
  humanitec_token:
    description: 'humanitec token'
    required: true
  humanitec_org:
    description: 'humanitec org'
    required: true
  image_name:
    description: 'image name'
    required: true
    default: ${{ github.event.repository.name }}

runs:
  using: "composite"
  steps:
    - name: Push to Humanitec
      run: ${{ github.action_path }}/../scripts/push-to-humanitec.sh ${{ inputs.humanitec_org }} ${{ inputs.humanitec_token }} ${{ inputs.image_name }}
      shell: sh
