name: 'Push image to Humanitec'
description: 'Push image to Humanitec'
inputs:
  humanitec_token:
    description: 'Humanitec token'
    required: true
  humanitec_org:
    description: 'Humanitec org'
    required: false
    default: ${{ github.event.repository.owner.login }}
  image_name:
    description: 'The name of the local and remote images. Defaults to the repository name'
    required: false
    default: ${{ github.event.repository.name }}
  image_stage:
    description: 'The build stage of the image. Defaults to "dist"'
    required: false
    default: dist

runs:
  using: "composite"
  steps:
    - name: Push to Humanitec
      run: ${{ github.action_path }}/../_scripts/push-to-humanitec.sh ${{ inputs.humanitec_org }} ${{ inputs.humanitec_token }} ${{ inputs.image_name }} ${{ inputs.image_stage }}
      shell: sh
