name: 'Build Docker image for Humanitec'
description: 'Build Docker image with docker cache'
inputs:
  humanitec_token:
    description: 'docker command line args'
    required: true
  image_name:
    description: 'image name'
    required: true
    default: ${{ github.event.repository.name }}

runs:
  using: "composite"
  steps:
    - run: ./scripts/push-to-humanitec.sh ${{ inputs.humanitec_token }} ${{ inputs.image_name }}
      shell: sh
