name: 'Run command in container'
description: 'Run command in container'
inputs:
  command:
    description: 'Command'
    required: true
  run_args:
    description: 'Docker run args'
    required: true
    default: ''
  image_name:
    description: 'Image name'
    required: true
    default: ${{ github.event.repository.name }}
  image_tag:
    description: "Image tag"
    required: true
    default: latest
  env_file:
    description: 'Env file'
    required: false
    default: /dev/null
  entrypoint:
    description: 'Entrypoint override'
    required: false

runs:
  using: "composite"
  steps:
    -  name: Run command ${{ inputs.entrypoint }} ${{ inputs.command }} in container
       run: ${{ github.action_path }}/../scripts/docker-run.sh "${{ inputs.image_name }}" "${{ inputs.image_tag }}" "${{ inputs.command }}" "${{ inputs.env_file }}" "${{ inputs.run_args }}" "${{ inputs.entrypoint }}"
       shell: sh
