name: 'Build Docker image for Humanitec'
description: 'Build Docker image with docker cache'
inputs:
  build-args:
    description: 'docker command line args'
    required: true
    default: ''
  project-root:
    description: 'projects root directory'
    required: true
    default: '.'
  build-context:
    description: 'build context'
    required: true
    default: '.'
  image-name:
    description: 'image name'
    required: true
    default: 'docker-image'

runs:
  using: "composite"
  steps:
    - uses: satackey/action-docker-layer-caching@v0.0.11
    - run: cd ${{ inputs.project-root }} && docker build ${{ inputs.build-args }} -t ${{ inputs.image-name }}:$(git rev-parse HEAD) ${{ inputs.build-context }}
      shell: bash
