name: Deploy PR to Humanitec
description: 'Deploy Pull Request to Humanitec'
inputs:
  humanitec_token:
    description: 'Humanitec secret token'
    required: true
  humanitec_org:
    description: 'Humanitec organization'
    required: false
    default: ${{ github.event.repository.owner.login }}
  app_id:
    description: 'Application ID on Humanitec'
    required: true
  environment_name:
    description: 'Environment to delete. Defaults to PR #'
    required: false
    default: ${{ github.event.number }}

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v6
      env:
        HUMANITEC_ORG: ${{ inputs.humanitec_org }}
        HUMANITEC_TOKEN: ${{ inputs.humanitec_token }}
      with:
        script: |
          const humanitec = require('${{ github.action_path }}/../_scripts/humanitec.js');
          const HUMANITEC_ORG = `${{ inputs.humanitec_org }}`;
          const APP_ID = `${{ inputs.app_id }}`;
          const ENV_ID = `${{ inputs.environment_name }}`;

          const status = await humanitec.deleteEnvironment(APP_ID, ENV_ID);
          if (status.status > 400) {
            console.error(`Cannot delete feature environment: ${JSON.stringify(status.body)}`);
            return;
          }
          
          console.info(`Deleted feature environment ${ENV_ID} for ${APP_ID}`);
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `Feature environment deleted.`
          });
