name: 'Create PR environment'
description: 'Create PR environment on PR open'
inputs:
  humanitec_token:
    description: 'humanitec access token'
    required: true
  humanitec_org:
    description: 'humanitec organization'
    required: true
  app_id:
    description: 'Application ID on Humanitec'
    required: true
  base_environment:
    description: 'Environment to clone from (usually production|preview)'
    required: true
  image_name:
    description: 'image name'
    required: true
    default: ${{ github.event.repository.name }}

runs:
  using: "composite"
  steps:
      - uses: actions/github-script@v6
        env:
          HUMANITEC_ORG: ${{ inputs.humanitec_org }}
          HUMANITEC_TOKEN: ${{ inputs.humanitec_token }}
        with:
          script: |
            const humanitec = require('${{ github.action_path }}/../scripts/humanitec.js');
            const BASE_ENV_ID = `${{ inputs.base_environment }}`;
            const HUMANITEC_ORG = `${{ inputs.humanitec_org }}`;
            const ENV_ID = `${context.issue.number}`;
            const APP_ID = `${{ inputs.app_id }}`;
            const IMAGE_ID = `${{ inputs.image_name }}`;
            const BRANCH_NAME = `${context.payload.pull_request.head.ref}`;
            const ENV_PATH = `/orgs/${HUMANITEC_ORG}/apps/${APP_ID}/envs/${ENV_ID}`;

            console.log(`Creating PR environment ${ENV_ID} for ${APP_ID} from ${BASE_ENV_ID}`);

            const env = await humanitec.cloneEnvironment(APP_ID, BASE_ENV_ID, ENV_ID);
            if (env.status > 400) {
              if (env.status == 409) {
                console.error(`Cannot create preview environment. Environment with ID "${ENV_ID}" already exists.`);
              } else {
                console.error(`Cannot create preview environment: ${JSON.stringify(env.body)}`);
              }
              return;
            }
            
            console.log(`Created preview environment: ${JSON.stringify(env.body)} `);
            console.log(`Creating automation rule ${ENV_ID} for ${APP_ID} from ${BASE_ENV_ID} branch ${BRANCH_NAME}`);
            const rule = await humanitec.addAutomationRule(APP_ID, ENV_ID, [IMAGE_ID], BRANCH_NAME);
            if (env.status > 400) {
              console.error(`Cannot create atomation rule in environment ${ENV_ID}: ${JSON.stringify(env.body)}`);
              return;
            }
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Created environment in Humanitec: https://app.humanitec.io${ENV_PATH}`
            });
