#!/bin/sh

set -e

IMAGE_NAME="$1"
IMAGE_TAG="$2"
COMMAND="$3"
ENV_FILE="$4"
RUN_ARGS="$5"
ENTRYPOINT_OVERRIDE="$6"

if [ -z "$ENTRYPOINT_OVERRIDE" ]; then
  ENTRYPOINT_ARG=""
  COMMAND_ARG="$COMMAND"
else
  ENTRYPOINT_ARG="--entrypoint $ENTRYPOINT_OVERRIDE $COMMAND"
  COMMAND_ARG=""
fi

docker run --rm --env-file "$ENV_FILE" $RUN_ARGS "$IMAGE_NAME:$IMAGE_TAG" $ENTRYPOINT_ARG $COMMAND_ARG
