name: 'Run command in container'
description: 'Run command in container'
inputs:
  command:
    description: 'command'
    required: true
  run_args:
    description: 'docker run args'
    required: true
    default: ''
  image_name:
    description: 'image name'
    required: true
    default: ${{ github.event.repository.name }}
  image_tag:
    description: "image tag"
    required: true
    default: latest

runs:
  using: "composite"
  steps:
    -  run: docker run --rm ${{ inputs.image_name }}:${{ inputs.image_tag }} ${{ inputs.run_args }} -- ${{ inputs.command }}
       shell: bash
