name: 'Run command in container'
description: 'Run command in container'
inputs:
  command:
    description: 'command'
    required: true
  run_args:
    description: 'docker run args'
    required: true
    default: ''
  image_name:
    description: 'image name'
    required: true
    default: ${{ github.event.repository.name }}
  image_tag:
    description: "image tag"
    required: true
    default: latest
  env_file:
    description: 'env file'
    required: false
    default: /dev/null

runs:
  using: "composite"
  steps:
    -  run: docker run --rm --env-file ${{ inputs.env_file }} ${{ inputs.run_args }} ${{ inputs.image_name }}:${{ inputs.image_tag }} -- ${{ inputs.command }}
       shell: bash
