name: 'Run command in container'
description: 'Run command in container'
inputs:
  command:
    description: 'command'
    required: true
  run_args:
    description: 'docker run args'
    required: true
    default: ''
  image_name:
    description: 'image name'
    required: true
    default: ${{ github.event.repository.name }}
  image_tag:
    description: "image tag"
    required: true
    default: latest
  env_file:
    description: 'env file'
    required: false
    default: /dev/null
  entrypoint:
    description: 'Entrypoint'
    required: true

runs:
  using: "composite"
  steps:
    -  name: Run command ${{ inputs.entrypoint }} ${{ inputs.command }} in container
       run: ${{ github.action_path }}/../scripts/docker-run.sh "${{ inputs.image_name }}" "${{ inputs.image_tag }}" "${{ inputs.command }}" "${{ inputs.env_file }}" "${{ inputs.run_args }}" "${{ inputs.entrypoint }}"
       shell: sh
