name: 'Build container image'
description: 'Build Docker image with docker cache'
inputs:
  build_args:
    description: 'Arguments passed to `docker build`'
    required: false
    default: ''
  build_context:
    description: 'Docker build context '
    required: false
    default: '.'
  image_name:
    description: 'Image name. Defaults to the repository name. Set it if you build multiple images in the same repository'
    required: false
    default: ${{ github.event.repository.name }}
  multi_stage:
    description: 'Whether to produce production/testing images from a multi-staged Dockerfile'
    required: false
    default: 'false'
  production_stage:
    description: 'Name of the production stage on multi-stage build'
    required: false
    default: production
  testing_stage:
    description: 'Name of the testing stage on multi-stage build'
    required: false
    default: testing
  testing_tag:
    description: 'Tag of the testing image for multi-stage builds'
    required: false
    default: testing

runs:
  using: "composite"
  steps:
    - uses: satackey/action-docker-layer-caching@v0.0.11
    - name: Building ${{ inputs.image_name }}:latest
      run: ${{ github.action_path }}/../scripts/docker-build.sh "${{ inputs.build_context }}" "${{ inputs.build_args }}" "${{ inputs.image_name }}" "${{ inputs.multi_stage }}" "${{ inputs.production_stage }}" "${{ inputs.testing_stage }}" "${{ inputs.testing_tag }}""
      shell: sh
