name: 'Initialize cache'
description: Initialize cache
inputs:
  github_token:
    description: 'Github token'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: test
      shell: sh
      run: echo "test" && echo "${{ inputs.github_token }}"
    - uses: jpribyl/action-docker-layer-caching@v0.1.1
      continue-on-error: true
    - name: clear artifact cache
      if: inputs.github_token != ''
      run: echo "Clearing artifact cache..." && gh cache delete --all
      shell: sh
      continue-on-error: true
      env:
        GH_TOKEN: ${{ inputs.github_token }}
    - run: docker rmi -f $(docker images | awk '$2 != "latest" && $2 != "testing" {print $3}') >/dev/null 2>&1 || exit 0
      shell: sh
    - run: docker builder prune -f
      shell: sh
