name: Test all actions
on: [push]
jobs:
  test-suite:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v1

      - name: Build local image
        uses: ./build-docker-image
        with:
          image-name: http-echo #optional
          project-root: ./test-app #optional
          build-context: . #optional
          build-args: --build-arg test=test #optional

      - name: Test if image is built successfully
        run:  if docker image ls | grep -q 'http-echo'; then exit 0; else exit 1; fi

      - name: Push to Humanitec
        uses: ./humanitec-push-image
        with:
          humanitec-token: ${{ secrets.HUMANITEC_TOKEN }}
          image-name: http-echo
