name: Test all actions
on: [push]
jobs:
  test-suite:
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test build local image
        uses: ./docker-build
        with:
          build_context: https://github.com/mendhak/docker-http-https-echo.git #optional

      - name: List images & containers
        run:  docker image ls && docker ps -a

      - name: Test non-e2e tests
        uses: ./docker-run-tests
        with:
          lint: echo 'test lint'
          unit: echo 'test unit'
          functional: echo 'test functional'
          static: echo 'test static'

#      - name: Test e2e test
#        uses: ./docker-run-tests
#        with:
#          e2e: echo 'e2e test'
#
#      - name: Test push to Humanitec
#        uses: ./humanitec-push-image
#        with:
#          humanitec_token: ${{ secrets.HUMANITEC_TOKEN }}
#          humanitec_org: checkout-charlie

      - name: List images & containers
        run:  docker image ls && docker ps -a
