name: Test all actions
on: [push]
jobs:
  test-suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test build local image
        uses: ./build-docker-image
        with:
          build_context: https://github.com/mendhak/docker-http-https-echo.git #optional

      - name: Test if image is built successfully
        run:  if docker image ls | grep -q '${{ github.event.repository.name }}'; then exit 0; else exit 1; fi

      - name: Test push to Humanitec
        uses: ./humanitec-push-image
        with:
          humanitec_token: ${{ secrets.HUMANITEC_TOKEN }}
