name: Test all actions
on: [push]
jobs:
  test-suite:
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test build local image
        uses: ./image-build
        with:
          image_name: github-actions-test
          build_context: https://github.com/mendhak/docker-http-https-echo.git

      - name: List images & containers
        run:  docker image ls && docker ps -a

      - name: Test non-e2e tests
        uses: ./run-tests
        with:
          image_name: github-actions-test
          image_tag: latest
          static: echo 'test static'
          unit: echo 'test unit'
          functional: echo 'test functional'

      - name: Show image exposed ports
        run: docker inspect --format='{{json .Config.ExposedPorts}}' "github-actions-test:latest" | jq 'keys[0]' | cut -d'/' -f1 | cut -d'"' -f2
        shell: bash

      - name: Test e2e test
        uses: ./run-tests
        with:
          image_name: github-actions-test
          e2e: echo 'e2e test'
          e2e_port: 8080
          image_tag: latest

      - name: Test push to Humanitec
        uses: ./humanitec-push-image
        with:
          image_name: github-actions-test
          humanitec_token: ${{ secrets.HUMANITEC_TOKEN }}
          humanitec_org: checkout-charlie
